level:
  name: automobileV2
  path: /Game/automobileV2.automobileV2
vehicles:
  bicycle:
  - name: StaticMeshActor_1
    default_transform:
      location:
        X: 0.0
        Y: 1170.0
        Z: 0.0
      rotation:
        Pitch: 0.0
        Yaw: -90.0
        Roll: 0.0
      scale:
        X: 0.38
        Y: 0.38
        Z: 0.38
    lock:
    - scale
  - name: StaticMeshActor_3
    default_transform:
      location:
        X: 0.0
        Y: 1160.0
        Z: 0.0
      rotation:
        Pitch: 0.0
        Yaw: 0.0
        Roll: 0.0
      scale:
        X: 21.82
        Y: 21.82
        Z: 21.82
    lock:
    - scale
  - name: StaticMeshActor_5
    default_transform:
      location:
        X: 0.0
        Y: 1370.0
        Z: 0.0
      rotation:
        Pitch: 0.0
        Yaw: 90.0
        Roll: 0.0
      scale:
        X: 2.25
        Y: 2.25
        Z: 2.25
    lock:
    - scale
  bus:
  - name: StaticMeshActor_7
    default_transform:
      location:
        X: 0.0
        Y: 1550.0
        Z: 0.0
      rotation:
        Pitch: 0.0
        Yaw: -90.0
        Roll: 0.0
      scale:
        X: 1.23
        Y: 1.23
        Z: 1.23
    lock:
    - scale
  - name: StaticMeshActor_9
    default_transform:
      location:
        X: 0.0
        Y: 1540.0
        Z: 0.0
      rotation:
        Pitch: 0.0
        Yaw: 90.0
        Roll: 0.0
      scale:
        X: 1.22
        Y: 1.22
        Z: 1.22
    lock:
    - scale
  - name: StaticMeshActor_11
    default_transform:
      location:
        X: 0.0
        Y: 1460.0
        Z: 0.0
      rotation:
        Pitch: 0.0
        Yaw: -90.0
        Roll: 0.0
      scale:
        X: 1.29
        Y: 1.29
        Z: 1.29
    lock:
    - scale
  car:
  - name: StaticMeshActor_13
    default_transform:
      location:
        X: 0.0
        Y: 1760.0
        Z: 0.0
      rotation:
        Pitch: 0.0
        Yaw: -90.0
        Roll: 0.0
      scale:
        X: 1.28
        Y: 1.28
        Z: 1.28
    lock:
    - scale
  - name: StaticMeshActor_19
    default_transform:
      location:
        X: 0.0
        Y: 1870.0
        Z: 0.0
      rotation:
        Pitch: 0.0
        Yaw: -90.0
        Roll: 0.0
      scale:
        X: 0.03
        Y: 0.03
        Z: 0.03
    lock:
    - scale
  - name: StaticMeshActor_29
    default_transform:
      location:
        X: 0.0
        Y: 1780.0
        Z: 0.0
      rotation:
        Pitch: 0.0
        Yaw: 0.0
        Roll: 0.0
      scale:
        X: 1.49
        Y: 1.49
        Z: 1.49
    lock:
    - scale
  - name: StaticMeshActor_33
    default_transform:
      location:
        X: 0.0
        Y: 1490.0
        Z: 0.0
      rotation:
        Pitch: 0.0
        Yaw: 0.0
        Roll: 0.0
      scale:
        X: 1.28
        Y: 1.28
        Z: 1.28
    lock:
    - scale
  - name: StaticMeshActor_39
    default_transform:
      location:
        X: 0.0
        Y: 1190.0
        Z: 0.0
      rotation:
        Pitch: 0.0
        Yaw: 0.0
        Roll: 0.0
      scale:
        X: 1.52
        Y: 1.52
        Z: 1.52
    lock:
    - scale
  - name: StaticMeshActor_34
    default_transform:
      location:
        X: 0.0
        Y: 1740.0
        Z: 0.0
      rotation:
        Pitch: 0.0
        Yaw: -90.0
        Roll: 0.0
      scale:
        X: 0.01
        Y: 0.01
        Z: 0.01
    lock:
    - scale
  - name: StaticMeshActor_26
    default_transform:
      location:
        X: 0.0
        Y: 1540.0
        Z: 0.0
      rotation:
        Pitch: 0.0
        Yaw: 90.0
        Roll: 0.0
      scale:
        X: 0.61
        Y: 0.61
        Z: 0.61
    lock:
    - scale
  - name: StaticMeshActor_23
    default_transform:
      location:
        X: 0.0
        Y: 1490.0
        Z: 0.0
      rotation:
        Pitch: 0.0
        Yaw: -90.0
        Roll: 0.0
      scale:
        X: 0.85
        Y: 0.85
        Z: 0.85
    lock:
    - scale
  - name: StaticMeshActor_18
    default_transform:
      location:
        X: 0.0
        Y: 1650.0
        Z: 0.0
      rotation:
        Pitch: 0.0
        Yaw: 0.0
        Roll: 0.0
      scale:
        X: 0.05
        Y: 0.05
        Z: 0.05
    lock:
    - scale
  motorcycle:
  - name: SkeletalMeshActor_5
    default_transform:
      location:
        X: 0.0
        Y: 1790.0
        Z: 0.0
      rotation:
        Pitch: 0.0
        Yaw: 180.0
        Roll: 0.0
      scale:
        X: 18.2
        Y: 18.2
        Z: 18.2
    lock:
    - scale
  - name: StaticMeshActor_2
    default_transform:
      location:
        X: 0.0
        Y: 2020.0
        Z: 0.0
      rotation:
        Pitch: 0.0
        Yaw: 90.0
        Roll: 0.0
      scale:
        X: 0.94
        Y: 0.94
        Z: 0.94
    lock:
    - scale
  - name: StaticMeshActor_8
    default_transform:
      location:
        X: 0.0
        Y: 1720.0
        Z: 0.0
      rotation:
        Pitch: 0.0
        Yaw: -90.0
        Roll: 0.0
      scale:
        X: 0.5
        Y: 0.5
        Z: 0.5
    lock:
    - scale
  truck:
  - name: StaticMeshActor_25
    default_transform:
      location:
        X: 0.0
        Y: 1930.0
        Z: 0.0
      rotation:
        Pitch: 0.0
        Yaw: 180.0
        Roll: 0.0
      scale:
        X: 0.03
        Y: 0.03
        Z: 0.03
    lock:
    - scale
  - name: StaticMeshActor_27
    default_transform:
      location:
        X: 0.0
        Y: 1740.0
        Z: 0.0
      rotation:
        Pitch: 0.0
        Yaw: -90.0
        Roll: 0.0
      scale:
        X: 1.41
        Y: 1.41
        Z: 1.41
    lock:
    - scale
  - name: StaticMeshActor_41
    default_transform:
      location:
        X: 0.0
        Y: 1320.0
        Z: 0.0
      rotation:
        Pitch: 0.0
        Yaw: 0.0
        Roll: 0.0
      scale:
        X: 1.34
        Y: 1.34
        Z: 1.34
    lock:
    - scale
